spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/synq_db
spring.datasource.username=postgres
spring.datasource.password=shahid19

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
